apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: node:14
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://<external-mongodb-url>:27017/mydatabase"
