apiVersion: v1
kind: Pod
metadata:
  name: nodejs-app-pod2
  labels:
    app: nodejs-app
spec:
  containers:
    - name: nodejs-app-container
      image: your-image:latest
      ports:
        - containerPort: 80
