apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-mongo-express
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-mongo-express
  template:
    metadata:
      labels:
        app: backend-mongo-express
    spec:
      serviceAccountName: app-service-account # Existing ServiceAccount
      containers:
        - name: mongo-express
          image: mongo-express:latest # Backend image
          ports:
            - containerPort: 8081
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: "user"
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: "password"
          command:
            - "/bin/sh"
            - "-c"
            - |
              export ME_CONFIG_MONGODB_URL="mongodb://${DB_USER}:${DB_PASSWORD}@mongo-service:27017/test" &&
              npm start
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"
