apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nodejs
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-nodejs
  template:
    metadata:
      labels:
        app: backend-nodejs
    spec:
      containers:
        - name: backend-nodejs
          image: mangalbhaskar/express-mongo-crud:v1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGO_URI
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: NODE_ENV
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD
          resources:
            requests:
              memory: "512Mi" # Minimum memory allocated to the container
              cpu: "250m" # Minimum CPU allocated to the container
            limits:
              memory: "1Gi" # Maximum memory the container can use
              cpu: "1" # Maximum CPU the container can use
