apiVersion: v1
kind: Service
metadata:
  name: backend-nodejs
  namespace: app
spec:
  selector:
    app: backend-nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP # Expose the service within the cluster
