apiVersion: v1
kind: Service
metadata:
  name: backend-mongo-express-service
  namespace: app
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30000 # Example port
  selector:
    app: backend-mongo-express
