apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: app
spec:
  serviceName: "mongo-service"
  replicas: 1 # Number of MongoDB instances
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0.12 # Replace with your actual MongoDB image
          ports:
            - containerPort: 27017 # Expose port 27017 (default MongoDB port)
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_INITDB_ROOT_PASSWORD
          resources:
            requests:
              memory: "256Mi" # Minimum memory allocated to the container
              cpu: "200m" # Minimum CPU allocated to the container
            limits:
              memory: "512Mi" # Maximum memory the container can use
              cpu: "500m" # Maximum CPU the container can use
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi # Persistent storage size
