apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: app
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None # Headless service for MongoDB StatefulSet
